name: UI Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant gradlew permission (Windows fix)
        run: git update-index --chmod=+x gradlew

      - name: Run tests
        run: .\gradlew.bat clean test